### ISSUE TITLE
请问下，扩展导入后提示这样，启用后左侧菜单栏就消失了

### ISSUE THREAD

**Issue by bfsz** [changzhong/extension-iframe-tabs#2]
php artisan admin:import iframe-tabs
Copied Directory [\vendor\changzhong\extension-iframe-tabs\resources\assets] To [\public\vendors\dcat-admin-extensions\iframe-tabs]
**Unable to locate publishable resources.**
Compiled views cleared!
The helper file [dcat_admin_ide_helper.php] created successfully.
Extension [Dcat\Admin\Extension\IframeTabs\IframeTabs] imported

请问下这是什么原因导致的，谢谢。

**Comment by changzhong** [comment]
直接访问你的域名下的/admin才会有左侧菜单，单独打开的页面没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "changzhong/extension-iframe-tabs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午12:06
收件人:&nbsp;"changzhong/extension-iframe-tabs"<extension-iframe-tabs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[changzhong/extension-iframe-tabs] 请问下，扩展导入后提示这样，启用后左侧菜单栏就消失了 (#2)





 
php artisan admin:import iframe-tabs
 Copied Directory [\vendor\changzhong\extension-iframe-tabs\resources\assets] To [\public\vendors\dcat-admin-extensions\iframe-tabs]
 Unable to locate publishable resources.
 Compiled views cleared!
 The helper file [dcat_admin_ide_helper.php] created successfully.
 Extension [Dcat\Admin\Extension\IframeTabs\IframeTabs] imported
 
请问下这是什么原因导致的，谢谢。

**Comment by bfsz** [comment]
> admin

多谢，问题已解决
